export const DS_COMPONENT_NAMES = new Set([
  "front/theme/wow-button-accent-border-image",
  "front/theme/wow-button-accent-sprite",
  "front/theme/wow-button-accent-border-image-mask",
  "front/theme/wow-button-base-primary-s-border-image",
  "front/theme/wow-button-base-primary-m-border-image",
  "front/theme/wow-button-base-primary-s-sprite",
  "front/theme/wow-button-base-primary-l-border-image",
  "front/theme/wow-button-base-primary-m-sprite",
  "front/theme/wow-button-base-primary-l-sprite",
  "front/theme/wow-button-base-secondary-s-sprite",
  "front/theme/wow-button-base-secondary-l-border-image",
  "front/theme/wow-button-base-secondary-m-border-image",
  "front/theme/wow-button-base-secondary-s-border-image",
  "front/theme/wow-button-base-secondary-m-sprite",
  "front/theme/wow-button-base-secondary-l-sprite",
  "front/theme/wow-button-base-vip-s-sprite",
  "front/theme/wow-button-base-vip-l-border-image",
  "front/theme/wow-button-base-vip-m-border-image",
  "front/theme/wow-button-base-vip-s-border-image",
  "front/theme/wow-button-base-vip-m-sprite",
  "front/theme/wow-button-base-vip-l-sprite",
  "front/theme/wow-button-base-danger-s-sprite",
  "front/theme/wow-button-base-danger-l-border-image",
  "front/theme/wow-button-base-danger-m-border-image",
  "front/theme/wow-button-base-danger-s-border-image",
  "front/theme/wow-button-base-danger-m-sprite",
  "front/theme/wow-button-base-danger-l-sprite",
  "front/theme/wow-button-navigation-primary-l-background-image",
  "front/theme/wow-button-navigation-primary-m-background-image",
  "front/theme/wow-button-navigation-primary-s-background-image",
  "front/theme/wow-button-navigation-secondary-l-background-image",
  "front/theme/wow-button-navigation-secondary-m-background-image",
  "front/theme/wow-button-navigation-secondary-s-background-image",
  "front/theme/wow-button-navigation-vip-l-background-image",
  "front/theme/wow-button-navigation-vip-m-background-image",
  "front/theme/wow-button-navigation-vip-s-background-image",
  "front/theme/wow-segment-control-secondary-s-sprite",
  "front/theme/wow-segment-control-secondary-l-border-image",
  "front/theme/wow-segment-control-secondary-m-border-image",
  "front/theme/wow-segment-control-secondary-s-border-image",
  "front/theme/wow-segment-control-secondary-m-sprite",
  "front/theme/wow-segment-control-secondary-l-sprite",
  "front/theme/wow-input-basic-sprite",
  "front/theme/wow-input-basic-border-image",
  "front/theme/wow-notification-border-image",
  "front/theme/wow-notification-sprite",
  "front/theme/wow-modal-default-border-image",
  "front/theme/wow-modal-default-border-sprite",
  "front/theme/wow-modal-default-overlay-image",
  "front/theme/wow-modal-halloween-border-image",
  "front/theme/wow-modal-halloween-border-sprite",
  "front/theme/wow-modal-halloween-overlay-image",
  "front/theme/wow-modal-newyear-border-image",
  "front/theme/wow-modal-newyear-border-sprite",
  "front/theme/wow-modal-newyear-overlay-image",
  ".item/wow-button-base-primary-s-border-image",
  ".item/wow-button-base-primary-m-border-image",
  ".item/wow-button-base-primary-l-border-image",
  ".item/wow-button-base-secondary-s-border-image",
  ".item/wow-button-base-secondary-m-border-image",
  ".item/wow-button-base-secondary-l-border-image",
  ".item/wow-button-base-vip-s-border-image",
  ".item/wow-button-base-vip-m-border-image",
  ".item/wow-button-base-vip-l-border-image",
  ".item/wow-button-base-danger-s-border-image",
  ".item/wow-button-base-danger-m-border-image",
  ".item/wow-button-base-danger-l-border-image",
  ".item/wow-button-accent-border-image",
  ".item/wow-button-accent-border-image-mask",
  ".item//wow-segment-control-secondary-s-border-image",
  ".item//wow-segment-control-secondary-m-border-image",
  ".item//wow-segment-control-secondary-l-border-image",
  ".item/wow-input-basic-border-image",
  ".item/wow-notification-border-image",
  ".item/wow-modal-default-border-image",
  ".item/wow-modal-newyear-border-image",
  ".item/wow-modal-halloween-border-image",
  ".item/game-card-border-image",
  ".item/sidebar-border-image",
  ".item/banner-border-image",
  ".item/banner-secondary-border-image",
  ".item/activity-card-border-image",
  ".item/base-card-border-image",
  ".item/small-card-border-image",
  "front/components/wow/game-card-sprite",
  "front/components/wow/game-card-border-image",
  "front/components/wow/sidebar-border-image",
  "front/components/wow/sidebar-sprite",
  "front/components/wow/sidebar-overlay-image",
  "front/components/wow/banner-overlay-image",
  "front/components/wow/banner-sprite",
  "front/components/wow/banner-secondary-sprite",
  "front/components/wow/banner-secondary-border-image",
  "front/components/wow/banner-border-image",
  "front/components/wow/bigwin-background",
  "front/components/wow/bigwin-background-mobile",
  "front/components/wow/provider-background-image",
  "front/components/wow/card-event-overlay-image",
  "front/components/wow/card-loyalty-overlay-image",
  "front/components/wow/menu-overlay-image",
  "front/components/wow/header-mobile-overlay-image",
  "front/components/wow/header-desktop-overlay-image",
  "front/components/wow/header-mobile-newyear-overlay-image",
  "front/components/wow/header-mobile-halloween-overlay-image",
  "front/components/wow/header-desktop-newyear-overlay-image",
  "front/components/wow/header-desktop-halloween-overlay-image",
  "front/components/wow/footer-bg",
  "front/components/wow/footer-bg-mobile",
  "front/components/wow/activity-card-sprite",
  "front/components/wow/activity-card-border-image",
  "front/components/wow/base-card-sprite",
  "front/components/wow/base-card-border-image",
  "front/components/wow/small-card-border-image",
  "front/components/wow/small-card-sprite",
  "front/components/wow/tournament-card-overlay-image",
  "front/components/wow/wheel-card-overlay-image",
  "front/components/wow/mission-card-overlay-image",
  "front/components/wow/lotteries-card-overlay-image",
  "front/components/wow/promo-card-overlay-image",
  "front/components/wow/calendar-card-overlay-image",
  "front/components/wow/store-card-overlay-image",
  "front/components/wow/activity-card-overlay-image",
  "front/components/wow/cashback-card-overlay-image",
  "front/components/wow/bonus-card-overlay-image",
  "front/components/wow/body-mobile",
  "front/components/wow/body-desktop",
  "front/components/wow/halloween-body-desktop",
  "front/components/wow/halloween-body-mobile",
  "front/components/wow/newyear-body-desktop",
  "front/components/wow/newyear-body-mobile",
  "_docCardHeader",
  "_swapContent",
  "WowAccentButton",
  "WowProgress",
  "Accordion",
  "Avatar",
  "Rakeback",
  "Badge — Primary",
  "Badge — Secondary",
  "Badge — Info",
  "Badge — Minor",
  "Badge — Success",
  "Badge — Attention",
  "Badge — Warning",
  "Badge — Danger",
  "Badge — Light",
  "Badge — Dark",
  "Badge — Transparent",
  "Badge — Jackpot",
  "Badge — VIP",
  "Button Fill — Primary",
  "Button Fill — Secondary",
  "Button Fill — VIP",
  "Button Fill — Danger",
  "Button Store — Basic",
  "Button Link — Primary",
  "Button Link — Secondary",
  "Button Navigation — Primary",
  "Button Navigation — Secondary",
  "Button Navigation — VIP",
  "Button Social",
  "Horizontal Buttons",
  "Vertical Buttons",
  "Game Image",
  "Countdown",
  "Counter — Primary",
  "Counter — Secondary",
  "Counter — Info",
  "Counter — Minor",
  "Counter — Success",
  "Counter — Attention",
  "Counter — Warning",
  "Counter — Danger",
  "Counter — Light",
  "Counter — Dark",
  "Counter — Transparent",
  "Counter — VIP",
  "Dots Bar",
  "Message — Basic",
  "Message — Primary",
  "Message — Info",
  "Message — Success",
  "Message — Attention",
  "Message — Warning",
  "Message — Danger",
  "Message — Minor",
  "Message Line",
  "Notification",
  "Icon Desktop",
  "Icon Mobile",
  "Preloader — Secondary",
  "Progress Bar — Primary",
  "Progress Bar — Secondary",
  "Progress Bar — Info",
  "Progress Bar — Minor",
  "Progress Bar — Success",
  "Progress Bar — Attention",
  "Progress Bar — VIP",
  "Progress Bar — Accent",
  "Progress Bar — Danger",
  "Progress Bar — Light",
  "Progress Round — Primary",
  "Progress Round — Secondary",
  "Progress Round — Info",
  "Progress Round — Minor",
  "Progress Round — Success",
  "Progress Round — Attention",
  "Progress Round — Danger",
  "Progress Round — Light",
  "Scrollbar",
  "Vertical Steps",
  "Horizonal Steps",
  "Header Table — Fill",
  "Header Table — Lineal",
  "Row Table — Fill",
  "Row Table — Lineal",
  "Table Modal",
  "Tabs Fill — Secondary",
  "Tabs Underline — Primary",
  "Tab Underline S — Primary",
  "Tab Underline M — Primary",
  "Tab Underline L — Primary",
  "Tab S — Secondary",
  "Tab M — Secondary",
  "Tab L — Secondary",
  "Tag — Fill",
  "Tag — Outline",
  "Tag — Ghost",
  "Tag — Ghost Secondary",
  "Title — Basic",
  "Title — VIP",
  "Row Dropdown S — Basic",
  "Row Dropdown M — Basic",
  "List S — Basic",
  "List M — Basic",
  "Icon Color Desktop — Modal",
  "Icon Color Mobile — Modal",
  "Status Desktop — Modal",
  "Status Mobile — Modal",
  "Modal",
  "Modal Fullscreen",
  "Header Desktop — Modal",
  "Header Mobile — Modal",
  "Body Desktop — Modal",
  "Body Mobile — Modal",
  "Tooltip",
  "Checkbox — Basic",
  "Checkbox — Primary",
  "Radiobutton — Basic",
  "Radiobutton — Primary",
  "Switcher — Basic",
  "Switcher — Primary",
  "Horizontal Field — Basic",
  "Input — Basic",
  "Input Multy — Basic",
  "Combobox — Basic",
  "Textaria  — Basic",
  "Vertical Field — Basic",
  "Dropdown",
]);